[package]
name = "sigar"
version = "0.0.2"
authors = ["Chris Brown <xoebus@xoeb.us>"]
description = "Rust bindings for libsigar for gathering system information."
homepage = "https://github.com/xoebus/rust-sigar"
repository = "https://github.com/xoebus/rust-sigar"
readme = "README.md"
license = "MIT"
links = "sigar"
build = "build.rs"

[lib]
name = "sigar"

[dependencies]
libc = "0.1.10"

[build-dependencies]
pkg-config = "0.3.5"
